import React,{useEffect,useMemo,useState}from'react'
import{createWorker}from'tesseract.js'
import{all,put,del,clear}from'./db'
import{uid,date,splitText,compress,url}from'./utils'
import'./styles.css'
const PS=['강의','블로그','재무관리','진로·자기계발','인간관계','삶의 태도','글쓰기','다시 보기']
export default function App(){
const[tab,setTab]=useState('home'),[books,setBooks]=useState([]),[records,setRecords]=useState([]),[toast,setToast]=useState(''),[modal,setModal]=useState(false)
const[bt,setBt]=useState(''),[ba,setBa]=useState(''),[bc,setBc]=useState(null),[book,setBook]=useState(''),[page,setPage]=useState('')
const[img,setImg]=useState(null),[text,setText]=useState(''),[sent,setSent]=useState([]),[chosen,setChosen]=useState([]),[status,setStatus]=useState(''),[prog,setProg]=useState(0)
const[thought,setThought]=useState(''),[mine,setMine]=useState(''),[tags,setTags]=useState(''),[purposes,setPurposes]=useState([]),[action,setAction]=useState(''),[saving,setSaving]=useState(false),[search,setSearch]=useState('')
useEffect(()=>{load()},[]);useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2200);return()=>clearTimeout(t)}},[toast])
async function load(){const[b,r]=await Promise.all([all('books'),all('records')]);setBooks(b.sort((x,y)=>y.createdAt-x.createdAt));setRecords(r.sort((x,y)=>y.createdAt-x.createdAt))}
const bm=useMemo(()=>Object.fromEntries(books.map(b=>[b.id,b])),[books])
const quote=chosen.length?chosen.sort((a,b)=>a-b).map(i=>sent[i]).join(' '):text
const filtered=records.filter(r=>[r.quote,r.thought,r.mine,r.action,bm[r.bookId]?.title,...(r.tags||[]),...(r.purposes||[])].filter(Boolean).join(' ').toLowerCase().includes(search.toLowerCase()))
async function addBook(e){e.preventDefault();if(!bt.trim())return setToast('책 제목을 입력하세요.');setSaving(true);try{let cover=null;if(bc)cover=await compress(bc,500,700,.62);await put('books',{id:uid(),title:bt.trim(),author:ba.trim(),cover,createdAt:Date.now()});setBt('');setBa('');setBc(null);setModal(false);await load();setToast('책을 등록했습니다.')}catch{setToast('등록에 실패했습니다.')}setSaving(false)}
async function ocr(file){if(!file)return;setStatus('사진을 준비하는 중…');setProg(0);setChosen([]);setSent([]);try{const[o,s]=await Promise.all([compress(file,1600,2100,.8),compress(file,900,1200,.58)]);setImg(s);const w=await createWorker('kor+eng',1,{logger:m=>{if(m.status==='recognizing text'){const p=Math.round((m.progress||0)*100);setProg(p);setStatus(`글자를 읽는 중… ${p}%`)}}});const{data}=await w.recognize(o);await w.terminate();const t=(data.text||'').trim();setText(t);const ss=splitText(t);setSent(ss);setStatus(ss.length?'원하는 문장을 선택하세요.':'직접 입력해주세요.');setProg(100)}catch(e){console.error(e);setStatus('인식에 실패했습니다. 직접 입력해주세요.')}}
async function save(){if(!book)return setToast('책을 선택하세요.');if(!quote.trim())return setToast('저장할 문장이 없습니다.');setSaving(true);try{await put('records',{id:uid(),bookId:book,page,quote:quote.trim(),thought:thought.trim(),mine:mine.trim(),tags:tags.split(',').map(x=>x.trim()).filter(Boolean),purposes,action:action.trim(),image:img,createdAt:Date.now()});setPage('');setImg(null);setText('');setSent([]);setChosen([]);setThought('');setMine('');setTags('');setPurposes([]);setAction('');await load();setToast('문장을 저장했습니다.');setTab('home')}catch{setToast('저장 실패. 입력은 유지됩니다.')}setSaving(false)}
async function remove(store,id){if(!confirm('삭제할까요?'))return;await del(store,id);await load()}
function card(r){return <div className="card" key={r.id}><div className="meta">{bm[r.bookId]?.title||'책 미지정'}{r.page?` · p.${r.page}`:''} · {date(r.createdAt)}</div><div className="quote">{r.quote}</div>{r.thought&&<div className="small"><b>내 생각</b> {r.thought}</div>}<div className="tags">{[...(r.purposes||[]),...(r.tags||[])].map(t=><span className="tag" key={t}>{t}</span>)}</div><button className="btn danger" style={{marginTop:12}} onClick={()=>remove('records',r.id)}>삭제</button></div>}
async function backup(){const blob=new Blob([JSON.stringify({version:2,books,records},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='문장씨앗2_백업.json';a.click()}
async function restore(f){try{const d=JSON.parse(await f.text());await clear('books');await clear('records');for(const x of d.books)await put('books',x);for(const x of d.records)await put('records',x);await load();setToast('복원했습니다.')}catch{setToast('백업 파일을 확인하세요.')}}
return <div className="app"><header><div className="brand"><div className="logo">🌱</div><div><h1>문장씨앗 2.0</h1><div className="sub">문장을 기록하고 생각을 연결하세요.</div></div></div></header><main>
{tab==='home'&&<><div className="hero"><h2>오늘도 한 문장을 심어볼까요?</h2><p>기록이 쌓일수록 나만의 관점과 콘텐츠가 선명해집니다.</p></div><div className="grid"><div className="stat"><b>{books.length}</b><span>책</span></div><div className="stat"><b>{records.length}</b><span>문장</span></div><div className="stat"><b>{records.filter(r=>r.thought).length}</b><span>생각</span></div></div><div className="section"><h3>최근 기록</h3></div>{records.slice(0,4).map(card)}{!records.length&&<div className="empty">첫 문장을 기록해보세요.</div>}</>}
{tab==='capture'&&<div className="card"><div className="section"><h3>문장 촬영·기록</h3></div><label>책</label><select value={book} onChange={e=>setBook(e.target.value)}><option value="">책 선택</option>{books.map(b=><option value={b.id} key={b.id}>{b.title}</option>)}</select><label>페이지 사진</label><div className="upload">
<div style={{fontSize:32,marginBottom:8}}>📚</div>
<div className="actions" style={{justifyContent:'center'}}>
<label className="btn" style={{display:'inline-block',margin:0}}>📷 사진 촬영
<input hidden type="file" accept="image/*" capture="environment" onChange={e=>ocr(e.target.files?.[0])}/></label>
<label className="btn secondary" style={{display:'inline-block',margin:0}}>🖼 사진첩에서 선택
<input hidden type="file" accept="image/*" onChange={e=>ocr(e.target.files?.[0])}/></label>
</div>
{img&&<img className="preview" src={url(img)}/>}
<p className="small">{status}</p>
{status&&<div className="progress"><i style={{width:prog+'%'}}/></div>}</div><label>페이지</label><input value={page} onChange={e=>setPage(e.target.value)}/>{sent.length>0&&<><label>저장할 문장 선택</label>{sent.map((s,i)=><label className={'sentence '+(chosen.includes(i)?'selected':'')} key={i}><input type="checkbox" checked={chosen.includes(i)} onChange={()=>setChosen(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i])}/><span>{s}</span></label>)}</>}<label>중요 원문</label><textarea value={quote} onChange={e=>{setText(e.target.value);setChosen([])}}/><label>내 생각</label><textarea value={thought} onChange={e=>setThought(e.target.value)}/><label>내 언어로</label><textarea value={mine} onChange={e=>setMine(e.target.value)}/><label>활용처</label><div className="tags">{PS.map(p=><button className="tag" style={purposes.includes(p)?{background:'#315c49',color:'white'}:{}} key={p} onClick={()=>setPurposes(x=>x.includes(p)?x.filter(v=>v!==p):[...x,p])}>{p}</button>)}</div><label>태그</label><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="쉼표로 구분"/><label>실천</label><textarea value={action} onChange={e=>setAction(e.target.value)}/><button className="btn full" disabled={saving} onClick={save}>{saving?'저장 중…':'문장 저장하기'}</button></div>}
{tab==='library'&&<><div className="section"><h3>문장 보관함</h3></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="검색"/>{filtered.map(card)}</>}
{tab==='books'&&<><div className="section"><h3>내 책</h3><button className="btn" onClick={()=>setModal(true)}>책 등록</button></div>{books.map(b=><div className="card book" key={b.id}><div className="cover">{b.cover?<img src={url(b.cover)}/>:'📚'}</div><div className="grow"><h4>{b.title}</h4><p>{b.author||'저자 미입력'} · 문장 {records.filter(r=>r.bookId===b.id).length}개</p></div><button className="btn danger" onClick={()=>remove('books',b.id)}>삭제</button></div>)}</>}
{tab==='settings'&&<><div className="section"><h3>데이터 관리</h3></div><div className="card"><p className="small">IndexedDB로 사진과 기록을 안정적으로 저장합니다. 아직 기기 간 자동 동기화는 지원하지 않습니다.</p><button className="btn" onClick={backup}>백업 받기</button><label className="btn secondary" style={{display:'inline-block',marginLeft:8}}>백업 복원<input hidden type="file" accept=".json" onChange={e=>restore(e.target.files?.[0])}/></label></div></>}
</main><nav><div className="nav">{[['home','⌂','홈'],['capture','＋','기록'],['library','▤','보관함'],['books','▥','책'],['settings','⚙','설정']].map(x=><button key={x[0]} className={tab===x[0]?'on':''} onClick={()=>setTab(x[0])}><b>{x[1]}</b>{x[2]}</button>)}</div></nav>{toast&&<div className="toast">{toast}</div>}{modal&&<dialog open><form className="modal" onSubmit={addBook}><div className="section"><h3>책 등록</h3><button type="button" className="btn secondary" onClick={()=>setModal(false)}>닫기</button></div><label>책 제목</label><input value={bt} onChange={e=>setBt(e.target.value)}/><label>저자</label><input value={ba} onChange={e=>setBa(e.target.value)}/><label>표지</label><input type="file" accept="image/*" capture="environment" onChange={e=>setBc(e.target.files?.[0]||null)}/><button className="btn full modal-submit" disabled={saving}>{saving?'등록 중…':'등록하기'}</button></form></dialog>}</div>}
